// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiErrorPayload = { 
/**
 * JSON crudo del backend convertido a String para compatibilidad total
 */
error_api: string, message: string, code: number, };
