// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type ClientResponse = { id: number, email: string, phone: string | null, address: string | null, notes: string | null, birthDate: string | null, clientType: string, code: string, user: User | null, };
