// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientRequest = { name: string, email: string, phone: string, address: string | null, notes: string | null, birthDate: string | null, clientType: string, flagUser: boolean | null, };
