// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoogleClientId } from "./GoogleClientId";

export type GoogleResponse = { data: GoogleClientId, success: boolean, message: string | null, };
