// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpResponseObject<T> = { success: boolean, message: string, data: T, status: number, timestamp: string, };
