// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginatedResponse } from "./PaginatedResponse";

export type HttpResponseApi<T> = { success: boolean, message: string, data: PaginatedResponse<T>, status: number, timestamp: string, };
