// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaginatedResponse<T> = { content: Array<T>, totalElements: bigint, totalPages: number, size: number, number: number, last: boolean, first: boolean, };
