// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Profile = { id: number, username: string, fullName: string, provider: string, passwordInit: string | null, avatar: string | null, address: string | null, phone: string | null, email: string | null, birthDate: string | null, };
