// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Employee } from "./Employee";
import type { Profile } from "./Profile";
import type { UserAuth } from "./UserAuth";

export type User = { profile: Profile, user: UserAuth, employee: Employee | null, };
