// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAuth = { id: number, enabled: boolean, provider: string, roles: Array<string>, token: string | null, };
