// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type UserPage = { content: Array<User>, total_elements: bigint, total_pages: number, current_page: number, };
