// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Employee } from "./Employee";

export type User = { id: number, username: string, token: string, fullName: string, phone: string | null, address: string | null, avatar: string | null, password: string | null, passwordInit: string | null, createdAt: string, updateAt: string | null, deletedAt: string | null, employee: Employee | null, roles: Array<string> | null, enabled: boolean | null, clientId: number | null, provider: string | null, };
